pipeline:
  deploy-loki:
    image: alpine
    agent:
      - arm64
    environment:
      HOST: 192.168.1.19
      USER: potentpi3
      DEST: /home/potentpi3
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - scp ./deploy/loki/docker-compose.yml $USER@$HOST:$DEST/
      - ssh $USER@$HOST 'docker compose -f ~/docker-compose.yml up -d'